# Generated by Django 3.0.7 on 2020-06-23 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='league',
            new_name='league_id',
        ),
        migrations.AddField(
            model_name='player',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='player',
            name='player_first',
            field=models.CharField(default='test first name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='player_last',
            field=models.CharField(default='test last name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structure',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='structure',
            name='cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='structure',
            name='hard_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='structure',
            name='league_bit_wallet_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='league_bit_wallet_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='league_node_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='league_node_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_bit_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_bit_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_cap_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_lux_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_reg_dues',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
