# Generated by Django 3.0.7 on 2020-06-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200623_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_salary',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='cap',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='hard_cap',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_cap_fee',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_lux_fee',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_reg_dues',
        ),
        migrations.AddField(
            model_name='player',
            name='player_sal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='structure',
            name='structure_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='structure',
            name='structure_hard_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='team',
            name='team_cap_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='team',
            name='team_lux_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='team',
            name='team_regular_dues',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='team',
            name='team_sal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
