# Generated by Django 3.0.7 on 2020-06-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200623_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_sal',
        ),
        migrations.AddField(
            model_name='player',
            name='player_sal_19_20',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='player',
            name='player_sal_20_21',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='player',
            name='player_sal_21_22',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='player',
            name='player_sal_22_23',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
