# Generated by Django 3.0.7 on 2020-06-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200624_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='RookieDraftStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rookie_draft_style', models.CharField(max_length=100)),
                ('rookie_draft_style_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='structure',
            name='rook_draft_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.RookieDraftStyle'),
        ),
    ]
