# Generated by Django 3.0.7 on 2020-06-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200624_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegSeasonDraftStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_draft_style', models.CharField(max_length=100)),
                ('reg_draft_style_desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
