# Generated by Django 3.0.7 on 2020-06-24 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_regseasondraftstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='reg_draft_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.RegSeasonDraftStyle'),
        ),
    ]
