# Generated by Django 3.0.7 on 2020-06-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_structure_reg_draft_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(default='default.jpg', upload_to='fan_team_pics'),
        ),
    ]
