# Generated by Django 3.0.7 on 2020-06-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200624_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(default='default_fan_team.jpg', upload_to='fan_team_pics'),
        ),
    ]
