# Generated by Django 3.0.7 on 2020-06-24 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200624_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_logo',
        ),
    ]
