# Generated by Django 3.0.7 on 2020-06-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_team_team_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='reg_draft_style',
            new_name='regular_draft_style',
        ),
    ]
