# Generated by Django 3.0.7 on 2020-06-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200625_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_full',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
