# Generated by Django 3.0.7 on 2020-06-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_player_player_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nba_team',
        ),
        migrations.AddField(
            model_name='player',
            name='player_nba_team',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
