# Generated by Django 3.0.7 on 2020-07-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200626_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
