# Generated by Django 3.0.7 on 2020-07-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200706_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fa_status',
            field=models.BooleanField(default=True),
        ),
    ]
