# Generated by Django 3.0.7 on 2020-07-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200713_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fa_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
