# Generated by Django 3.0.7 on 2020-07-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200713_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='fa_status',
            new_name='_fa_status',
        ),
    ]
