# Generated by Django 3.0.7 on 2020-07-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200713_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='_fa_status',
        ),
    ]
