# Generated by Django 3.0.7 on 2020-07-13 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_remove_player__fa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_unit_value',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
