# Generated by Django 3.0.7 on 2020-07-23 17:43

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_player_player_unit_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlayersUpdateView',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Player')),
            ],
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, django.views.generic.edit.UpdateView, 'blog.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_sal_19_20',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_sal_20_21',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_sal_21_22',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_sal_22_23',
            field=models.IntegerField(default=0),
        ),
    ]
