# Generated by Django 3.0.7 on 2020-07-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20200723_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='two_point_perc',
            field=models.FloatField(default=0),
        ),
    ]
