# Generated by Django 3.0.7 on 2020-07-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_player_two_point_perc'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='c_week_3pm',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='c_week_ast',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='c_week_ato',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='c_week_blk',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='c_week_fg_per',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='c_week_ft_per',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='c_week_pts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='c_week_reb',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='c_week_stl',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
