# Generated by Django 3.0.7 on 2020-07-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20200730_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='NbaTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamID', models.PositiveSmallIntegerField(null=True)),
                ('Key', models.CharField(blank=True, max_length=4, null=True)),
                ('Active', models.BooleanField()),
                ('City', models.CharField(blank=True, max_length=25, null=True)),
                ('Name', models.CharField(blank=True, max_length=25, null=True)),
                ('LeagueID', models.PositiveSmallIntegerField(null=True)),
                ('StadiumID', models.PositiveSmallIntegerField(null=True)),
                ('Conference', models.CharField(blank=True, max_length=25, null=True)),
                ('Division', models.CharField(blank=True, max_length=25, null=True)),
                ('PrimaryColor', models.CharField(blank=True, max_length=25, null=True)),
                ('SecondaryColor', models.CharField(blank=True, max_length=25, null=True)),
                ('TertiaryColor', models.CharField(blank=True, max_length=25, null=True)),
                ('QuaternaryColor', models.CharField(blank=True, max_length=25, null=True)),
                ('WikipediaLogoUrl', models.CharField(blank=True, max_length=200, null=True)),
                ('GlobalTeamID', models.PositiveSmallIntegerField(null=True)),
                ('NbaDotComTeamID', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
