# Generated by Django 3.0.7 on 2020-07-31 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20200731_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nbateams',
        ),
    ]
